#!/usr/bin/env python3
#
# ChibiOS ROMFS image generator.
#

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import sys
from dataclasses import dataclass
from typing import NoReturn


C_KEYWORDS = {
    "auto", "break", "case", "char", "const", "continue", "default", "do",
    "double", "else", "enum", "extern", "float", "for", "goto", "if",
    "inline", "int", "long", "register", "restrict", "return", "short",
    "signed", "sizeof", "static", "struct", "switch", "typedef", "union",
    "unsigned", "void", "volatile", "while", "_Alignas", "_Alignof",
    "_Atomic", "_Bool", "_Complex", "_Generic", "_Imaginary", "_Noreturn",
    "_Static_assert", "_Thread_local",
}

IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True)
class FileEntry:
    name: str
    data: bytes
    mode: str


@dataclass(frozen=True)
class DirEntry:
    path: str
    files: tuple[FileEntry, ...]


def fail(message: str) -> NoReturn:
    raise SystemExit(f"mkromfs: error: {message}")


def validate_namespace(path: Path) -> str:
    namespace = path.name
    if not namespace:
        fail("input directory must have a non-empty leaf name")
    if not IDENTIFIER_RE.match(namespace):
        fail(
            f"directory name '{namespace}' is not a valid C identifier, "
            "allowed form is [A-Za-z_][A-Za-z0-9_]*"
        )
    if namespace in C_KEYWORDS:
        fail(f"directory name '{namespace}' is a reserved C keyword")
    return namespace


def escape_c_string(text: str) -> str:
    out: list[str] = []
    for b in text.encode("utf-8"):
        if 32 <= b <= 126 and b not in (34, 92):
            out.append(chr(b))
        elif b == 34:
            out.append(r"\"")
        elif b == 92:
            out.append(r"\\")
        elif b == 9:
            out.append(r"\t")
        elif b == 10:
            out.append(r"\n")
        elif b == 13:
            out.append(r"\r")
        else:
            out.append(f"\\x{b:02x}")
    return '"' + "".join(out) + '"'


def format_data_array(data: bytes) -> str:
    lines: list[str] = []
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk))
    return ",\n".join(lines)


def posix_path(root: Path, entry: Path) -> str:
    relative = entry.relative_to(root)
    if str(relative) == ".":
        return "/"
    return "/" + relative.as_posix()


def file_mode(entry: Path) -> str:
    mode = "VFS_MODE_S_IRUSR"
    if os.access(entry, os.X_OK):
        mode += " | VFS_MODE_S_IXUSR"
    return mode


def scan_dir(root: Path, current: Path) -> list[DirEntry]:
    subdirs: list[Path] = []
    files: list[FileEntry] = []

    for entry in sorted(current.iterdir(), key=lambda item: item.name):
        if entry.is_symlink():
            fail(f"symbolic links are not supported: {entry}")
        if entry.is_dir():
            subdirs.append(entry)
        elif entry.is_file():
            files.append(
                FileEntry(
                    name=entry.name,
                    data=entry.read_bytes(),
                    mode=file_mode(entry),
                )
            )
        else:
            fail(f"unsupported filesystem object: {entry}")

    entries = [
        DirEntry(path=posix_path(root, current), files=tuple(files))
    ]
    for subdir in subdirs:
        entries.extend(scan_dir(root, subdir))
    return entries


def emit_header(namespace: str) -> str:
    guard = f"{namespace.upper()}_ROMFS_H"

    return f"""/*
    Generated by tools/mkromfs/mkromfs.py. Do not edit manually.
*/

#ifndef {guard}
#define {guard}

#include "vfs.h"

#ifdef __cplusplus
extern "C" {{
#endif

extern const vfs_romfs_tree_t {namespace}_romfs;

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
"""


def emit_source(namespace: str, header_name: str, dirs: list[DirEntry]) -> str:
    lines: list[str] = []

    lines.append("/*")
    lines.append("    Generated by tools/mkromfs/mkromfs.py. Do not edit manually.")
    lines.append("*/")
    lines.append("")
    lines.append(f'#include "{header_name}"')
    lines.append("")

    for dir_index, directory in enumerate(dirs):
        for file_index, file_entry in enumerate(directory.files):
            if file_entry.data:
                lines.append(
                    f"static const uint8_t {namespace}_file_{dir_index}_{file_index}_data[] = {{"
                )
                lines.append(format_data_array(file_entry.data))
                lines.append("};")
                lines.append("")

        lines.append(
            f"static const vfs_romfs_file_desc_t {namespace}_dir_{dir_index}_files[] = {{"
        )
        if directory.files:
            for file_index, file_entry in enumerate(directory.files):
                if file_entry.data:
                    data_symbol = f"{namespace}_file_{dir_index}_{file_index}_data"
                else:
                    data_symbol = "NULL"
                lines.append("  {")
                lines.append(
                    f"    .name = {escape_c_string(file_entry.name)},"
                )
                lines.append(f"    .mode = {file_entry.mode},")
                lines.append("    .flags = 0U,")
                lines.append(f"    .size = (vfs_offset_t){len(file_entry.data)},")
                lines.append(f"    .data = {data_symbol},")
                lines.append("    .ops = NULL,")
                lines.append("    .arg = NULL,")
                lines.append("  },")
        lines.append("};")
        lines.append("")

    lines.append(f"static const vfs_romfs_dir_desc_t {namespace}_dirs[] = {{")
    for dir_index, directory in enumerate(dirs):
        lines.append("  {")
        lines.append(f"    .path = {escape_c_string(directory.path)},")
        lines.append(f"    .files = {namespace}_dir_{dir_index}_files,")
        lines.append(f"    .files_num = {len(directory.files)}U,")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append(f"const vfs_romfs_tree_t {namespace}_romfs = {{")
    lines.append(f"  .dirs = {namespace}_dirs,")
    lines.append(f"  .dirs_num = {len(dirs)}U,")
    lines.append("};")
    lines.append("")

    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a ChibiOS ROMFS C image from a directory tree."
    )
    parser.add_argument("input_dir", help="Source directory to convert.")
    parser.add_argument(
        "output_dir",
        nargs="?",
        default=".",
        help="Destination directory for the generated .c/.h files.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    input_dir = Path(args.input_dir).resolve()
    if not input_dir.exists():
        fail(f"input directory does not exist: {input_dir}")
    if not input_dir.is_dir():
        fail(f"input path is not a directory: {input_dir}")

    namespace = validate_namespace(input_dir)
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    dirs = sorted(scan_dir(input_dir, input_dir), key=lambda item: item.path)
    header_name = f"{namespace}_romfs.h"
    source_name = f"{namespace}_romfs.c"

    header_path = output_dir / header_name
    source_path = output_dir / source_name

    header_path.write_text(emit_header(namespace), encoding="utf-8", newline="\n")
    source_path.write_text(
        emit_source(namespace, header_name, dirs),
        encoding="utf-8",
        newline="\n",
    )

    print(header_path)
    print(source_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
