##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32L053-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32l053_discovery all
	@echo ====================================================================
	@echo
	@echo === Building for STM32L151-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32l151_discovery all
	@echo ====================================================================
	@echo
	@echo === Building for STM32L476-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32l476_discovery all
	@echo ====================================================================
	@echo
	@echo === Building for STM32F051-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32f051_discovery all
	@echo ====================================================================
	@echo
	@echo === Building for STM32F103-Olimex ==================================
	@make --no-print-directory -f Makefile-stm32f103_olimex all
	@echo ====================================================================
	@echo
	@echo === Building for STM32F303-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32f303_discovery all
	@echo ====================================================================
	@echo
	@echo === Building for STM32F373-Eval ====================================
	@make --no-print-directory -f Makefile-stm32f373_eval all
	@echo ====================================================================
	@echo
	@echo === Building for STM32F407-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32f407_discovery all
	@echo ====================================================================
	@echo
	@echo === Building for STM32F429-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32f429_discovery all
	@echo ====================================================================
	@echo
	@echo === Building for STM32F746-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32f746_discovery all
	@echo ====================================================================
	@echo

clean:
	@echo
	-@make --no-print-directory -f Makefile-stm32l053_discovery clean
	@echo
	-@make --no-print-directory -f Makefile-stm32l151_discovery clean
	@echo
	-@make --no-print-directory -f Makefile-stm32l476_discovery clean
	@echo
	-@make --no-print-directory -f Makefile-stm32f051_discovery clean
	@echo
	-@make --no-print-directory -f Makefile-stm32f103_olimex clean
	@echo
	-@make --no-print-directory -f Makefile-stm32f303_discovery clean
	@echo
	-@make --no-print-directory -f Makefile-stm32f373_eval clean
	@echo
	-@make --no-print-directory -f Makefile-stm32f407_discovery clean
	@echo
	-@make --no-print-directory -f Makefile-stm32f429_discovery clean
	@echo
	-@make --no-print-directory -f Makefile-stm32f746_discovery clean
	@echo

#
##############################################################################
