##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for ARMv7-M ===========================================
	+@make --no-print-directory -f ./make/ARMv7-M.make all
	@echo ====================================================================
	@echo

clean:
	@echo
	+@make --no-print-directory -f ./make/ARMv7-M.make clean
	@echo

#
##############################################################################
