/*  THIS FILE WAS GENERATED BY THE DATALIGHT RELIANCE EDGE CONFIGURATION
    UTILITY.  DO NOT MODIFY.

    Generated by configuration utility version 2.02
*/
/** @file
*/

#include "hal.h"

#if (HAL_USE_SDMMC == TRUE)
#include "sama_sdmmc_lld.h"
#if SDMMC_USE_RELEDGE_LIB == 1
#include <redfs.h>
#include <redconf.h>
#include <redtypes.h>
#include <redmacs.h>
#include <redvolume.h>


const VOLCONF gaRedVolConf[REDCONF_VOLUME_COUNT] =
{
    {
    		SDMMC_BLOCK_SIZE, 	//ulSectorSize
			1048576U, 			//ullSectorCount
			0U,					//ullSectorOffset
			false,				//fAtomicSectorWrite
			1024U,				//ulInodeCount
			2U,					//bBlockIoRetries
			"CHIBIVOL"
    }
};

#endif
#endif

