##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32C031C6-Nucleo144 =============================
	+@make --no-print-directory -f make/stm32c031c6_nucleo64.make all
	@echo ====================================================================
	@echo

clean:
	@echo
	+@make --no-print-directory -f make/stm32c031c6_nucleo64.make clean
	@echo
#
##############################################################################
