##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32H563ZI-Nucleo144 =============================
	+@make --no-print-directory -f make/stm32h563zi_nucleo144.make all
	@echo ====================================================================
	@echo

clean:
	@echo
	+@make --no-print-directory -f make/stm32h563zi_nucleo144.make clean
	@echo
#
##############################################################################
