/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/**
 * @file    sandbox/hal_gpt_lld.h
 * @brief   SandBox GPT subsystem low level driver header.
 *
 * @addtogroup HAL_GPT
 * @{
 */

#ifndef HAL_GPT_LLD_H
#define HAL_GPT_LLD_H

#if HAL_USE_GPT || defined(__DOXYGEN__)

/*===========================================================================*/
/* Driver constants.                                                         */
/*===========================================================================*/

/*===========================================================================*/
/* Driver pre-compile time settings.                                         */
/*===========================================================================*/

/**
 * @name    Configuration options
 * @{
 */
/**
 * @brief   GPT1 driver enable switch.
 * @details If set to @p TRUE the support for VGPT1 is included.
 * @note    The default is @p FALSE.
 */
#if !defined(VIO_GPT_USE_VGPT1) || defined(__DOXYGEN__)
#define VIO_GPT_USE_VGPT1                   FALSE
#endif

/**
 * @brief   GPT1 virtual IRQ number.
 * @details Must match with the IRQ number generated by the host.
 */
#if !defined(VIO_VGPT1_IRQ) || defined(__DOXYGEN__)
#define VIO_VGPT1_IRQ                       13
#endif
/** @} */

/*===========================================================================*/
/* Derived constants and error checks.                                       */
/*===========================================================================*/

#if !VIO_GPT_USE_VGPT1
#error "GPT driver activated but no VGPT peripheral assigned"
#endif

/*===========================================================================*/
/* Driver data structures and types.                                         */
/*===========================================================================*/

/*===========================================================================*/
/* Driver macros.                                                            */
/*===========================================================================*/

/**
 * @brief   Low level fields of the GPT configuration structure.
 * @note    In the VIO port the actual configuration is host-owned, the
 *          sandbox mirrors only the portable fields.
 */
#define gpt_lld_config_fields

/**
 * @brief   Low level fields of the GPT driver structure.
 */
#define gpt_lld_driver_fields                                               \
  /* Number of the associated VGPT.*/                                       \
  uint32_t                  nvgpt;                                          \
  /* Buffer for the local copy of the driver configuration.*/               \
  hal_gpt_config_t          cfgbuf;                                         \
  /* Last programmed interval.*/                                            \
  gptcnt_t                  interval

/**
 * @brief   Changes the interval of GPT peripheral.
 *
 * @param[in] gptp      pointer to a @p hal_gpt_driver_c object
 * @param[in] interval  new cycle time in timer ticks
 *
 * @notapi
 */
#define gpt_lld_change_interval(gptp, interval)                             \
  gpt_lld_change_interval_impl(gptp, interval)

/**
 * @brief   Returns the interval of GPT peripheral.
 *
 * @param[in] gptp      pointer to a @p hal_gpt_driver_c object
 * @return              The current interval.
 *
 * @notapi
 */
#define gpt_lld_get_interval(gptp) ((gptcnt_t)((gptp)->interval))

/**
 * @brief   Returns the counter value of GPT peripheral.
 *
 * @param[in] gptp      pointer to a @p hal_gpt_driver_c object
 * @return              The current counter value.
 *
 * @notapi
 */
#define gpt_lld_get_counter(gptp) gpt_lld_get_counter_impl(gptp)

/*===========================================================================*/
/* External declarations.                                                    */
/*===========================================================================*/

#if VIO_GPT_USE_VGPT1 && !defined(__DOXYGEN__)
extern hal_gpt_driver_c GPTD1;
#endif

#ifdef __cplusplus
extern "C" {
#endif
  void gpt_lld_init(void);
  msg_t gpt_lld_start(hal_gpt_driver_c *gptp);
  void gpt_lld_stop(hal_gpt_driver_c *gptp);
  const hal_gpt_config_t *gpt_lld_setcfg(hal_gpt_driver_c *gptp,
                                         const hal_gpt_config_t *config);
  const hal_gpt_config_t *gpt_lld_selcfg(hal_gpt_driver_c *gptp,
                                         unsigned cfgnum);
  void gpt_lld_set_callback(hal_gpt_driver_c *gptp, drv_cb_t cb);
  void gpt_lld_change_interval_impl(hal_gpt_driver_c *gptp,
                                    gptcnt_t interval);
  gptcnt_t gpt_lld_get_counter_impl(hal_gpt_driver_c *gptp);
  void gpt_lld_start_timer(hal_gpt_driver_c *gptp, gptcnt_t interval);
  void gpt_lld_stop_timer(hal_gpt_driver_c *gptp);
  void gpt_lld_polled_delay(hal_gpt_driver_c *gptp, gptcnt_t interval);
#ifdef __cplusplus
}
#endif

#endif /* HAL_USE_GPT */

#endif /* HAL_GPT_LLD_H */

/** @} */
