/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/**
 * @file    sandbox/hal_eth_lld.h
 * @brief   Sandbox ETH subsystem low level driver header.
 *
 * @addtogroup ETH
 * @{
 */

#ifndef HAL_ETH_LLD_H
#define HAL_ETH_LLD_H

#if HAL_USE_ETH || defined(__DOXYGEN__)

/*===========================================================================*/
/* Driver constants.                                                         */
/*===========================================================================*/

/**
 * @brief   Zero-copy support flag.
 */
#define ETH_SUPPORTS_ZERO_COPY              FALSE

/**
 * @brief   Mirrored ETH configuration has a MAC address.
 */
#define VIO_ETH_CFGF_MAC_ADDRESS            (1U << 0)

/*===========================================================================*/
/* Driver pre-compile time settings.                                         */
/*===========================================================================*/

/**
 * @name    VETH configuration options
 * @{
 */
/**
 * @brief   ETH1 driver enable switch.
 * @details If set to @p TRUE the support for VETH1 is included.
 * @note    The default is @p FALSE.
 */
#if !defined(VIO_ETH_USE_VETH1) || defined(__DOXYGEN__)
#define VIO_ETH_USE_VETH1                   FALSE
#endif

/**
 * @brief   ETH2 driver enable switch.
 * @details If set to @p TRUE the support for VETH2 is included.
 * @note    The default is @p FALSE.
 */
#if !defined(VIO_ETH_USE_VETH2) || defined(__DOXYGEN__)
#define VIO_ETH_USE_VETH2                   FALSE
#endif

/**
 * @brief   ETH1 virtual IRQ number.
 * @details Must match with the IRQ number generated by the host.
 */
#if !defined(VIO_VETH1_IRQ) || defined(__DOXYGEN__)
#define VIO_VETH1_IRQ                       10
#endif

/**
 * @brief   ETH2 virtual IRQ number.
 * @details Must match with the IRQ number generated by the host.
 */
#if !defined(VIO_VETH2_IRQ) || defined(__DOXYGEN__)
#define VIO_VETH2_IRQ                       11
#endif
/** @} */

/*===========================================================================*/
/* Derived constants and error checks.                                       */
/*===========================================================================*/

#if !VIO_ETH_USE_VETH1 && !VIO_ETH_USE_VETH2
#error "ETH driver activated but no VETH peripheral assigned"
#endif

/*===========================================================================*/
/* Driver data structures and types.                                         */
/*===========================================================================*/

/**
 * @brief   Type of a mirrored VIO ETH configuration.
 */
typedef struct vio_eth_config {
  uint32_t                  flags;
  uint8_t                   mac_address[6];
  uint8_t                   reserved[2];
} vio_eth_config_t;

/*===========================================================================*/
/* Driver macros.                                                            */
/*===========================================================================*/

/**
 * @brief   Low level fields of the ETH driver structure.
 */
#define eth_lld_driver_fields                                               \
  /* Number of the associated VETH.*/                                       \
  uint32_t                  nveth;                                          \
  /* Local copy of the selected configuration.*/                            \
  hal_eth_config_t          cfgbuf;                                         \
  /* Backing storage for the mirrored MAC address.*/                        \
  uint8_t                   cfgmac[6]

/**
 * @brief   Low level fields of the ETH configuration structure.
 * @note    In the VIO port configuration changes are limited to selecting
 *          one of the host-defined configurations, explicit @p setcfg
 *          requests are intentionally unsupported.
 */
#define eth_lld_config_fields

/*===========================================================================*/
/* External declarations.                                                    */
/*===========================================================================*/

#if VIO_ETH_USE_VETH1 && !defined(__DOXYGEN__)
extern hal_eth_driver_c ETHD1;
#endif

#if VIO_ETH_USE_VETH2 && !defined(__DOXYGEN__)
extern hal_eth_driver_c ETHD2;
#endif

#ifdef __cplusplus
extern "C" {
#endif
  void eth_lld_init(void);
  msg_t eth_lld_start(hal_eth_driver_c *ethp);
  void eth_lld_stop(hal_eth_driver_c *ethp);
  const hal_eth_config_t *eth_lld_setcfg(hal_eth_driver_c *ethp,
                                         const hal_eth_config_t *config);
  const hal_eth_config_t *eth_lld_selcfg(hal_eth_driver_c *ethp,
                                         unsigned cfgnum);
  eth_receive_handle_t eth_lld_get_receive_handle(hal_eth_driver_c *ethp);
  eth_transmit_handle_t eth_lld_get_transmit_handle(hal_eth_driver_c *ethp);
  bool eth_lld_is_receive_handle_valid(hal_eth_driver_c *ethp,
                                       eth_receive_handle_t rxh);
  bool eth_lld_is_transmit_handle_valid(hal_eth_driver_c *ethp,
                                        eth_transmit_handle_t txh);
  void eth_lld_release_receive_handle(hal_eth_driver_c *ethp,
                                      eth_receive_handle_t rxh);
  void eth_lld_release_transmit_handle(hal_eth_driver_c *ethp,
                                       eth_transmit_handle_t txh);
  size_t eth_lld_read_receive_handle(hal_eth_driver_c *ethp,
                                     eth_receive_handle_t rxh,
                                     uint8_t *bp, size_t n);
  size_t eth_lld_write_transmit_handle(hal_eth_driver_c *ethp,
                                       eth_transmit_handle_t txh,
                                       const uint8_t *bp, size_t n);
  bool eth_lld_poll_link_status(hal_eth_driver_c *ethp);
#if (ETH_SUPPORTS_ZERO_COPY == TRUE) || defined(__DOXYGEN__)
  const uint8_t *eth_lld_get_receive_buffer(hal_eth_driver_c *ethp,
                                            eth_receive_handle_t rxh,
                                            size_t *sizep);
  uint8_t *eth_lld_get_transmit_buffer(hal_eth_driver_c *ethp,
                                       eth_transmit_handle_t txh,
                                       size_t *sizep);
#endif
#ifdef __cplusplus
}
#endif

#endif /* HAL_USE_ETH */

#endif /* HAL_ETH_LLD_H */

/** @} */
