/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/**
 * @file    sandbox/hal_sio_lld.h
 * @brief   Sandbox SIO subsystem low level driver header.
 *
 * @addtogroup SIO
 * @{
 */

#ifndef HAL_SIO_LLD_H
#define HAL_SIO_LLD_H

#if (HAL_USE_SIO == TRUE) || defined(__DOXYGEN__)

/*===========================================================================*/
/* Driver constants.                                                         */
/*===========================================================================*/

/*===========================================================================*/
/* Driver pre-compile time settings.                                         */
/*===========================================================================*/

/**
 * @name    VSIO configuration options
 * @{
 */
/**
 * @brief   SIO driver 1 enable switch.
 * @details If set to @p TRUE the support for VUART1 is included.
 * @note    The default is @p FALSE.
 */
#if !defined(VIO_SIO_USE_VUART1) || defined(__DOXYGEN__)
#define VIO_SIO_USE_VUART1                  FALSE
#endif

/**
 * @brief   SIO driver 2 enable switch.
 * @details If set to @p TRUE the support for VUART2 is included.
 * @note    The default is @p FALSE.
 */
#if !defined(VIO_SIO_USE_VUART2) || defined(__DOXYGEN__)
#define VIO_SIO_USE_VUART2                  FALSE
#endif

/**
 * @brief   SIO driver 1 virtual IRQ number.
 * @details If set to @p TRUE the support for VUART1 is included.
 * @note    Must match with the IRQ number generated by the host.
 */
#if !defined(VIO_SIO_VUART1_IRQ) || defined(__DOXYGEN__)
#define VIO_SIO_VUART1_IRQ                  8
#endif

/**
 * @brief   SIO driver 2 virtual IRQ number.
 * @details If set to @p TRUE the support for VUART1 is included.
 * @note    Must match with the IRQ number generated by the host.
 */
#if !defined(VIO_SIO_VUART2_IRQ) || defined(__DOXYGEN__)
#define VIO_SIO_VUART2_IRQ                  9
#endif
/** @} */

/*===========================================================================*/
/* Derived constants and error checks.                                       */
/*===========================================================================*/

#if !VIO_SIO_USE_VUART1 && !VIO_SIO_USE_VUART2
#error "SIO driver activated but no VUART peripheral assigned"
#endif

/*===========================================================================*/
/* Driver data structures and types.                                         */
/*===========================================================================*/

/*===========================================================================*/
/* Driver macros.                                                            */
/*===========================================================================*/

/**
 * @brief   Low level fields of the SIO driver structure.
 */
#define sio_lld_driver_fields                                               \
  /* Number of the associated VUART.*/                                      \
  uint32_t                  nvuart;                                         \
  /* Buffer for the local copy of the driver configuration.*/               \
  hal_sio_config_t          cfgbuf

/**
 * @brief   Low level fields of the SIO configuration structure.
 */
#define sio_lld_config_fields

/*===========================================================================*/
/* External declarations.                                                    */
/*===========================================================================*/

#if (VIO_SIO_USE_VUART1 == TRUE) && !defined(__DOXYGEN__)
extern hal_sio_driver_c SIOD1;
#endif

#if (VIO_SIO_USE_VUART2 == TRUE) && !defined(__DOXYGEN__)
extern hal_sio_driver_c SIOD2;
#endif

#ifdef __cplusplus
extern "C" {
#endif
  void sio_lld_init(void);
  msg_t  sio_lld_start(hal_sio_driver_c *siop);
  void sio_lld_stop(hal_sio_driver_c *siop);
  const hal_sio_config_t *sio_lld_setcfg(hal_sio_driver_c *siop,
                                         const hal_sio_config_t *config);
  const hal_sio_config_t *sio_lld_selcfg(hal_sio_driver_c *siop, unsigned cfgnum);
  bool sio_lld_is_rx_empty(hal_sio_driver_c *siop);
  bool sio_lld_is_rx_idle(hal_sio_driver_c *siop);
  bool sio_lld_has_rx_errors(hal_sio_driver_c *siop);
  bool sio_lld_is_tx_full(hal_sio_driver_c *siop);
  bool sio_lld_is_tx_ongoing(hal_sio_driver_c *siop);
  void sio_lld_update_enable_flags(hal_sio_driver_c *siop);
  sioevents_t sio_lld_get_and_clear_errors(hal_sio_driver_c *siop);
  sioevents_t sio_lld_get_and_clear_events(hal_sio_driver_c *siop,
                                           sioevents_t events);
  sioevents_t sio_lld_get_events(hal_sio_driver_c *siop);
  size_t sio_lld_read(hal_sio_driver_c *siop, uint8_t *buffer, size_t n);
  size_t sio_lld_write(hal_sio_driver_c *siop, const uint8_t *buffer, size_t n);
  msg_t sio_lld_get(hal_sio_driver_c *siop);
  void sio_lld_put(hal_sio_driver_c *siop, uint_fast16_t data);
  msg_t sio_lld_control(hal_sio_driver_c *siop, unsigned int operation, void *arg);
  void sio_lld_serve_interrupt(hal_sio_driver_c *siop);
#ifdef __cplusplus
}
#endif

#endif /* HAL_USE_SIO == TRUE */

#endif /* HAL_SIO_LLD_H */

/** @} */
