/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/**
 * @file    sandbox/hal_i2c_lld.h
 * @brief   SandBox I2C subsystem low level driver header.
 *
 * @addtogroup HAL_I2C
 * @{
 */

#ifndef HAL_I2C_LLD_H
#define HAL_I2C_LLD_H

#if HAL_USE_I2C || defined(__DOXYGEN__)

/*===========================================================================*/
/* Driver constants.                                                         */
/*===========================================================================*/

/**
 * @brief   This I2C LLD does not support slave mode.
 */
#define I2C_SUPPORTS_SLAVE_MODE             FALSE

/*===========================================================================*/
/* Driver pre-compile time settings.                                         */
/*===========================================================================*/

/**
 * @name    Configuration options
 * @{
 */
/**
 * @brief   I2C1 driver enable switch.
 * @details If set to @p TRUE the support for VI2C1 is included.
 * @note    The default is @p FALSE.
 */
#if !defined(VIO_I2C_USE_VI2C1) || defined(__DOXYGEN__)
#define VIO_I2C_USE_VI2C1                   FALSE
#endif

/**
 * @brief   I2C1 virtual IRQ number.
 * @details Must match with the IRQ number generated by the host.
 */
#if !defined(VIO_VI2C1_IRQ) || defined(__DOXYGEN__)
#define VIO_VI2C1_IRQ                       14
#endif
/** @} */

/*===========================================================================*/
/* Derived constants and error checks.                                       */
/*===========================================================================*/

#if !VIO_I2C_USE_VI2C1
#error "I2C driver activated but no VI2C peripheral assigned"
#endif

/*===========================================================================*/
/* Driver data structures and types.                                         */
/*===========================================================================*/

/*===========================================================================*/
/* Driver macros.                                                            */
/*===========================================================================*/

/**
 * @brief   Low level fields of the I2C configuration structure.
 * @note    In the VIO port the actual configuration is host-owned.
 */
#define i2c_lld_config_fields

/**
 * @brief   Low level fields of the I2C driver structure.
 */
#define i2c_lld_driver_fields                                               \
  /* Number of the associated VI2C.*/                                       \
  uint32_t                  nvi2c;                                          \
  /* Buffer for the local copy of the driver configuration.*/               \
  hal_i2c_config_t          cfgbuf

/**
 * @brief   Returns the active configuration.
 *
 * @param[in] i2cp      pointer to the @p hal_i2c_driver_c object
 *
 * @notapi
 */
#define i2c_lld_getcfg(i2cp) ((const hal_i2c_config_t *)((i2cp)->config))

/*===========================================================================*/
/* External declarations.                                                    */
/*===========================================================================*/

#if VIO_I2C_USE_VI2C1 && !defined(__DOXYGEN__)
extern hal_i2c_driver_c I2CD1;
#endif

#ifdef __cplusplus
extern "C" {
#endif
  void i2c_lld_init(void);
  msg_t i2c_lld_start(hal_i2c_driver_c *i2cp);
  void i2c_lld_stop(hal_i2c_driver_c *i2cp);
  const hal_i2c_config_t *i2c_lld_setcfg(hal_i2c_driver_c *i2cp,
                                         const hal_i2c_config_t *config);
  const hal_i2c_config_t *i2c_lld_selcfg(hal_i2c_driver_c *i2cp,
                                         unsigned cfgnum);
  void i2c_lld_set_callback(hal_i2c_driver_c *i2cp, drv_cb_t cb);
  msg_t i2c_lld_start_master_transmit(hal_i2c_driver_c *i2cp, i2caddr_t addr,
                                      const uint8_t *txbuf, size_t txbytes,
                                      uint8_t *rxbuf, size_t rxbytes);
  msg_t i2c_lld_start_master_receive(hal_i2c_driver_c *i2cp, i2caddr_t addr,
                                     uint8_t *rxbuf, size_t rxbytes);
  msg_t i2c_lld_stop_transfer(hal_i2c_driver_c *i2cp);
#ifdef __cplusplus
}
#endif

#endif /* HAL_USE_I2C */

#endif /* HAL_I2C_LLD_H */

/** @} */
