##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32L476-Discovery ===============================
	+@make --no-print-directory -f Makefile-stm32l476_discovery all
	@echo ====================================================================
	@echo

clean:
	@echo
	+@make --no-print-directory -f Makefile-stm32l476_discovery clean
	@echo

#
##############################################################################
