/*
 * Minimal config for ChibiOS Pico SDK bindings.
 */

#define HAS_GPIO_COPROCESSOR 0
#define HAS_HSTX 0
#define LIB_FREERTOS_KERNEL 0
#define NUM_BOOT_LOCKS 0
#define PICO_BOOTROM_LOCKING_ENABLED 0
#define PICO_COMBINED_DOCS 0
#define PICO_IE_26_29_UNCHANGED_ON_RESET 0
#define PICO_SECURE 0
#define PICO_TIME_DEFAULT_ALARM_POOL_DISABLED 0
#define PICO_USE_GPIO_COPROCESSOR 0
#define PICO_USE_STACK_GUARDS 0

#ifndef LIB_PICO_MULTICORE
#define LIB_PICO_MULTICORE 0
#endif

#ifndef PICO_NO_FLASH
#define PICO_NO_FLASH 0
#endif

#include "boards/pico.h"
