##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32F746-Discovery ===============================
	@make --no-print-directory -f Makefile-stm32f746_discovery all
	@echo ====================================================================
	@echo

clean:
	@echo
	-@make --no-print-directory -f Makefile-stm32f746_discovery clean
	@echo

#
##############################################################################
