/*
    Generated by tools/mkromfs/mkromfs.py. Do not edit manually.
*/

#ifndef HTTP_ROMFS_H
#define HTTP_ROMFS_H

#include "vfs.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const vfs_romfs_tree_t http_romfs;

#ifdef __cplusplus
}
#endif

#endif /* HTTP_ROMFS_H */
