##############################################################################
# Options for test configurations
#

DEFS_CFG1 =
DEFS_CFG2 = -DCH_CFG_OPTIMIZE_SPEED=FALSE
DEFS_CFG3 = -DCH_CFG_TIME_QUANTUM=0
DEFS_CFG4 = -DCH_CFG_USE_REGISTRY=FALSE -DCH_CFG_USE_DYNAMIC=FALSE
DEFS_CFG5 = -DCH_CFG_USE_TM=FALSE
DEFS_CFG6 = -DCH_CFG_USE_SEMAPHORES=FALSE -DCH_CFG_USE_MAILBOXES=FALSE -DCH_CFG_USE_OBJ_FIFOS=FALSE -DCH_CFG_USE_OBJ_CACHES=FALSE -DCH_CFG_USE_JOBS=FALSE
DEFS_CFG7 = -DCH_CFG_USE_SEMAPHORES_PRIORITY=TRUE
DEFS_CFG8 = -DCH_CFG_USE_MUTEXES=FALSE -DCH_CFG_USE_CONDVARS=FALSE
DEFS_CFG9 = -DCH_CFG_USE_MUTEXES_RECURSIVE=TRUE
DEFS_CFG10 = -DCH_CFG_USE_CONDVARS=FALSE
DEFS_CFG11 = -DCH_CFG_USE_CONDVARS_TIMEOUT=FALSE
DEFS_CFG12 = -DCH_CFG_USE_EVENTS=FALSE
DEFS_CFG13 = -DCH_CFG_USE_EVENTS_TIMEOUT=FALSE
DEFS_CFG14 = -DCH_CFG_USE_MESSAGES=FALSE -DCH_CFG_USE_DELEGATES=FALSE
DEFS_CFG15 = -DCH_CFG_USE_MESSAGES_PRIORITY=TRUE
DEFS_CFG16 = -DCH_CFG_USE_MAILBOXES=FALSE -DCH_CFG_USE_OBJ_FIFOS=FALSE -DCH_CFG_USE_JOBS=FALSE
DEFS_CFG17 = -DCH_CFG_USE_MEMCORE=FALSE -DCH_CFG_USE_MEMPOOLS=FALSE -DCH_CFG_USE_HEAP=FALSE -DCH_CFG_USE_DYNAMIC=FALSE -DCH_CFG_USE_OBJ_FIFOS=FALSE -DCH_CFG_USE_JOBS=FALSE -DCH_CFG_USE_FACTORY=FALSE
DEFS_CFG18 = -DCH_CFG_USE_MEMPOOLS=FALSE -DCH_CFG_USE_HEAP=FALSE -DCH_CFG_USE_DYNAMIC=FALSE -DCH_CFG_USE_OBJ_FIFOS=FALSE -DCH_CFG_USE_JOBS=FALSE -DCH_CFG_USE_FACTORY=FALSE
DEFS_CFG19 = -DCH_CFG_USE_MEMPOOLS=FALSE -DCH_CFG_USE_OBJ_FIFOS=FALSE -DCH_CFG_USE_JOBS=FALSE -DCH_CFG_USE_FACTORY=FALSE
DEFS_CFG20 = -DCH_CFG_USE_HEAP=FALSE -DCH_CFG_USE_FACTORY=FALSE
DEFS_CFG21 = -DCH_CFG_USE_DYNAMIC=FALSE
DEFS_CFG22 = -DCH_DBG_STATISTICS=TRUE
DEFS_CFG23 = -DCH_DBG_SYSTEM_STATE_CHECK=TRUE
DEFS_CFG24 = -DCH_DBG_ENABLE_CHECKS=TRUE
DEFS_CFG25 = -DCH_DBG_ENABLE_ASSERTS=TRUE
DEFS_CFG26 = -DCH_DBG_TRACE_MASK=CH_DBG_TRACE_MASK_ALL
#DEFS_CFG27 = -DCH_DBG_ENABLE_STACK_CHECK=TRUE
DEFS_CFG28 = -DCH_DBG_FILL_THREADS=TRUE
DEFS_CFG29 = -DCH_DBG_THREADS_PROFILING=FALSE
DEFS_CFG30 = -DCH_DBG_SYSTEM_STATE_CHECK=TRUE -DCH_DBG_ENABLE_CHECKS=TRUE -DCH_DBG_ENABLE_ASSERTS=TRUE -DCH_DBG_TRACE_MASK=CH_DBG_TRACE_MASK_ALL -DCH_DBG_FILL_THREADS=TRUE
DEFS_CFG31 = -DCH_CFG_ST_RESOLUTION=16
DEFS_CFG32 = -DCH_CFG_ST_RESOLUTION=16 -DCH_CFG_INTERVALS_SIZE=64
DEFS_CFG33 = -DCH_CFG_INTERVALS_SIZE=64
DEFS_CFG34 = -DCH_CFG_USE_OBJ_FIFOS=FALSE
DEFS_CFG35 = -DCH_CFG_USE_FACTORY=FALSE

#
# Options for test configurations
##############################################################################
