##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32WB55RG_Nucleo68 =============================
	+@make --no-print-directory -f ./make/stm32wb55rg_nucleo68.make all
	@echo ====================================================================
	@echo

clean:
	@echo
	+@make --no-print-directory -f ./make/stm32wb55rg_nucleo68.make clean
	@echo

#
##############################################################################
